In [1]:
import numpy as np
import pandas as pd
import h2o

In [2]:
# Set seed
np.random.seed(123)

In [3]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: java version "1.8.0_181"; Java(TM) SE Runtime Environment (build 1.8.0_181-b13); Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
  Starting server from /home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpm5du3obp
  JVM stdout: /tmp/tmpm5du3obp/h2o_hp_started_from_python.out
  JVM stderr: /tmp/tmpm5du3obp/h2o_hp_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321... successful.


--------------------------  ----------------------------------------
H2O cluster uptime:         07 secs
H2O cluster timezone:       Asia/Kolkata
H2O data parsing timezone:  UTC
H2O cluster version:        3.22.1.1
H2O cluster version age:    28 days, 1 hour and 37 minutes
H2O cluster name:           H2O_from_python_hp_1zakeo
H2O cluster total nodes:    1
H2O cluster free memory:    1.714 Gb
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://127.0.0.1:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         XGBoost, Algos, AutoML, Core V3, Core V4
Python version:             3.6.4 final
--------------------------  ----------------------------------------

In [4]:
N = 1000

In [5]:
bloodTypes = ['A','O','AB','B']

In [6]:
d = pd.DataFrame({'id':[i for i in range(1,1001)],'bloodType':[bloodTypes[i%len(bloodTypes)] for i in range(1,1001)]})

In [7]:
d.head(5)

id bloodType
0   1         O
1   2        AB
2   3         B
3   4         A
4   5         O

In [9]:
bloodTypes = ['A','A','A','O','O','O','AB','B']

In [10]:
bloodTypes = bloodTypes*(round(N/8))

In [11]:
ages = np.random.randint(low=18,high=65,size=N)

In [13]:
ages[:5]

array([63, 20, 46, 52, 56])

In [14]:
healthyEating = np.random.normal(loc=5,scale=2,size=N)

In [15]:
healthyEating[healthyEating<0] = 0

In [16]:
healthyEating[healthyEating>9] = 9

In [17]:
healthyEating = healthyEating.round().astype(int)

In [18]:
np.bincount(healthyEating.astype(int))

array([  8,  31,  60, 113, 178, 202, 191, 122,  65,  30])

In [19]:
lifeStyle = np.random.normal(loc=5,scale=2,size=N)

In [20]:
lifeStyle[ages<30]=lifeStyle[ages<30]+1

In [21]:
lifeStyle[lifeStyle<0] = 0

In [22]:
lifeStyle[lifeStyle>9] = 9

In [23]:
lifeStyle=lifeStyle.round().astype(int)

In [24]:
income = ((ages*3)**2) + 20000 #Base salary

In [25]:
income = income + healthyEating*500

In [26]:
income = income - lifeStyle*300

In [27]:
income = income + np.random.randint(low=0,high=5000,size=N)

In [28]:
income = income.round(decimals=-2).astype(int)

In [29]:
income[:5]

array([59600, 26600, 40300, 45800, 51500])

In [30]:
d = {'bloodType': bloodTypes, 'age': ages,'healthyEating': healthyEating,

'lifeStyle':lifeStyle,'income':income}

In [31]:
df = pd.DataFrame(data=d)

In [32]:
people = h2o.H2OFrame(df,destination_frame='people')

Parse progress: |█████████████████████████████████████████████████████████| 100%
